### ISSUE TITLE
when enumerating the result rows, is this the only way to hand back the results?

### ISSUE THREAD

**Issue by aventurella** [bordoley/SQLitePCL.pretty#29]
It looks like the rows are disposable, so you can't async: `stmt.Query().ToList()`. That will give you back how many rows, but not the data.

This is the only way I have been able to get the results back from async stmt:

```csharp
public async Task<List<MyRow>> DoStuff()
{
    var myRows = new List<MyRow>();
    Func<object, object> rowParser = delegate(object result) { 
        var row = (IReadOnlyList<IResultSetValue>)result;
        var id = row[0].ToInt();
        var firstName = row[1].ToString();
        var lastName = row[2].ToString();
        
        myRows.Add(new MyRow{
            Id = id,
            FirstName = firstName,
            LastName = lastName
        });
        
        return null;
    };

    await QueryAsync("SELECT Id, FirstName, LastName From Author", rowParser);
    return myRows;
}

public async Task  QueryAsync(string sql, Func<object, object> rowParser)
{
            var db = GetMyAsyncConnection();
            var stmt = await db.PrepareStatementAsync(sql);
            await stmt.Use(s => {
                while (s.MoveNext())
                {
                    if (parseRow != null)
                        parseRow(s.Current);
                }
            });
}
```

**Comment by bordoley** [comment]
Woot first real bug on this project! Exciting.

I need to document this better, but the ISQLiteValue objects returned by both the synchronous and asynchronous versions are ephemeral to the state of the underlying SQLite stmt iterator. That is to say that the ISQLiteValue is a pointer to the current row of the enumeration always. Once the enumeration completes it essentially points to a SQLite null value. The reason is to avoid unintentionally allocating a large buffer of memory in managed code in the case that the associated sqlite value is a large blob. Instead SQLitePCL.pretty requires you to transform the values as you iterate through the result set either synchronously or asynchronously.


In your specific case I would try the following (may have typos):

```CSharp
IAsyncDatabaseConnection db = GetMyAsyncConnection();

// on the UI thread
var rows = await db.Query("SELECT Id, FirstName, LastName From Author").Select(x =>
   // This transformation occurs synchronously on the underlying task thread the sql statement is
  // being enumerated on.
    new MyRow{
            Id = x[0].ToInt(),
            FirstName =x[1].ToString(),
            LastName = x[2].ToString()
        }).ToList();
return rows;
// back on the ui thread
```
If you would prefer to reuse the same prepared statement asynchronously you do the following:

```CSharp
IAsyncDatabaseConnection db = GetMyAsyncConnection();

// Though not strictly required, you should always track the lifecycle of statements and dispose them
// before disposing the database.
using (var stmt = await db.PrepareStatementAsync("SELECT Id, FirstName, LastName From Author"))
{
    var rows = await stmt.Query().Select(x =>
        new MyRow{
                Id = x[0].ToInt(),
                FirstName =x[1].ToString(),
                LastName = x[2].ToString()
            }).ToList();
    return rows;
}
```

Also I'm in the process of implementing a port/fork of the sqlite-net table mapped ORM to SQLitePCL.pretty that should be available sometime in the next week or so and will make these simple use cases far easier. If you have any follow up questions feel free to ask. Please resolve this if you have no other issues.

**Comment by aventurella** [comment]
Thanks for the info! I can just pass the delegate to the Select() I think, that's a great idea. I actually need it for a tiny ORM thing I am doing. Looked though your ORM code as well, can't wait till you release it. 

Thanks again!

**Comment by bordoley** [comment]
If you have a chance can you check out the ORM in master. I think its almost there in terms of an API i'd want to support. Any feedback is appreciated.

**Comment by aventurella** [comment]
Looking at your ORM code... 

I'm relatively new to C#, picked it up, put it down over the last few years, but you are doing some clever things here, I like it! It taught me some things I didn't know about. Love the use of the GetColumnName extension method (PropertyInfo) in your Linq Expression Extension CompileExpr. Well played!

**Comment by bordoley** [comment]
I spoke too soon and ended up doing a major refactor last night that finally sits well with me :P I pushed a pre-release to nuget today as well. I don't expect to make any more api changes now. Only bug fixes.
