### ISSUE TITLE
SQLite-Net Missing Features

### ISSUE THREAD

**Issue by nberardi** [bordoley/SQLitePCL.pretty#33]
This is not really an issue, but more of a question I had after reading your README.  Can you provide a list or point me to a resource of missing features that SQLite-Net is missing over SQLitePCL.pretty?

**Comment by bordoley** [comment]
Its been so long since I've looked at SQLite-NET. Off the top of my head, I know that it doesn't support some of the more obscure APIs that raw provides, custom collation functions, progress handlers, query interrupts, scalar and aggregate functions, WAL, blob read/writes using the C# Stream API, backup api, etc. The async API I've implemented supports cancellation tokens which I don't believe SQLite-Net supports.

All that said I think the more fundamental difference is the approach in using the API. SQLite-Net is designed with the use of its ORM in mind. I think the API provided by pretty is more flexible and in a more modern C# style. Its also layered so you can choose to only use the sync API, without brining in the Async dependency. I personally think the way I've implemented Async on top of RX is more powerful, as I allow you to dispatch multiple sql queries in parallel asynchronously and guarantee in order operation due to the use of an asynchronous operations queue (similar to the one used in akavache) vs. blocking a task thread and waiting for lock as is done in SQLite-Net.

I also prefer my take on an ORM. The key difference here, is that my "ORM" is really more of a SQL DSL that is used to generate SQL query strings that can then be prepared. This allows you to reuse prepared statements and cache them yourself for reuse. It also supports the builder pattern, so that your DAO objects can actually be immutable, which is a unique feature across any ORM I've ever used.

Finally, and I think this is the biggest win, I spent a lot of time getting resource management "right". SQLiteDatabaseConnection tracks all its prepared statements, blobs, back ups etc. Though all those interfaces are disposable, when you dispose an IDatabaseConnection you are pretty much guaranteed for it to cleanup everything correctly without throwing exceptions. It even implements a finalizer so if you leak the database connection it will cleanup all the database resources (though I highly discourage that of course).

**Comment by bordoley** [comment]
Oh and of course SQLitePCL.pretty actually has a documented API: http://bordoley.github.io/SQLitePCL.pretty.Documentation/Help/html/R_Project_Documentation.htm

**Comment by bordoley** [comment]
And how could I forget, I support foreign key constraints defined in the ORM table mapping definition. Although constraint is limited to being a long that is the PK value of the column in the other table. See: https://github.com/bordoley/SQLitePCL.pretty/blob/master/SQLitePCL.pretty.tests/OrmTests/QueryTests.Joins.cs

**Comment by bordoley** [comment]
If you do end up using pretty, let me know. I'm definitely motivated to help out with its use.
