### ISSUE TITLE
Update to latest SQLitePCL.raw

### ISSUE THREAD

**Issue by aitchDashGee** [bordoley/SQLitePCL.pretty#36]
First of all, thank you very much for a great SQLite API library! :)
My main reason for using yours over Frank Krueger's sqlite-net-pcl is the blob stream support, to save allocations and GC when reading large amounts of large byte arrays, like images.

So, SQLitePCL.raw has gone 1.0 and beyond now, and in the process the structure changed a bit. All NuGet packages got new names, and thus SQLitePCL.pretty is left out of the update chain. Any plans on supporting SQLitePCL.raw 1.x+?

**Comment by bordoley** [comment]
I'll look into this over the week or so. What is your time frame for needing the 1.x upgrade? I likely will have time end of next week to work on this.

**Comment by aitchDashGee** [comment]
As it is right now at least, I personally have no specific time frame.
As I understand from @ericsink, there are changes in raw to support Android 7 properly. So, eventually when Android 7 devices start to come out, it will certainly be of interest to upgrade.

**Comment by bordoley** [comment]
@ericsink: Is SQLitePCLRaw.core the main PCL? Is the best option to take on a dependency on SQLitePCLRaw.bundle_green and call SQLitePCL.Batteries.Init(); internally in my lib, or can I make this more flexible, only depend on Raw.core and let users choose what underlying bundles to support etc.? On iOS does bundle_green use a version sqlite provided by you? As I recall there are library functions that I depend upon that are not supported in the version provided by Apple, but I don't recall the specifics.

**Comment by ericsink** [comment]
bundle_green uses the system SQLite on iOS.  If you want a bundle that includes a SQLite build on every platform, use bundle_e_sqlite3.  I prefer this approach, because I like the idea that my app is using the same SQLite build on all platforms.  That said, current versions of iOS are including a more recent version of SQLite than they used to.  (Not that I can remember which version it is.)

Yes, the main assembly is in SQLitePCLRaw.core.  You can just take a dep on that one and just let users choose a bundle.  This is a very clean way to go, IMHO, but it does require the users to make an initialization call.

**Comment by bordoley** [comment]
@ericsink In terms of cross platform support, is PCL 259 still considered the most general platform to target? I haven't done much .NET dev lately, and as part of this release I would like to make sure I support as many platforms as possible.

**Comment by ericsink** [comment]
Yes, 259 is good.

Actually the new way is netstandard, which replaces PCLs. But that would
be somewhat more effort. I'll plan to take a look at your build setup and
see what would be involved.

E

**Comment by bordoley** [comment]
I updated to SQLitePCLRaw.core in this commit: http://github.com/bordoley/SQLitePCL.pretty/commit/1c17b9f040d57befa77248f3fd47eca8cbb6723c

**Comment by aitchDashGee** [comment]
Sweet! Will take it for a spin sometime later this week. Thanks a bunch!

**Comment by bordoley** [comment]
I still need to push a release, unless you want to build from source. I'll try to get around to that in the middle of the week. Waiting for some feedback from eric on netstandard still.

**Comment by ericsink** [comment]
Since you're on PCL 259, it would *probably* be correct to just:

1.  Put another copy of your DLL in lib/netstandard1.0 in each of your nuspec files
2.  Add a dependency group for netstandard1.0 in each nuspec file, with a dep on NetStandard.Library.

But I'm not 100% sure.  I'd be a little more confident if, in the steps above, if you chance "netstandard1.0" to "netstandard1.1", but still not 100%.

Bottom line, a somewhat more careful approach would include things like:

1.  Modify your build system to actually build for netstandard and see if it goes okay
2.  Er, testing  :-)

But then you'd have to get your hands quite a bit dirtier, and if you're not currently doing much .NET stuff, that'll be more painful.

I could help with this and send you a PR, but not right away.

Alternatively, staying as a Profile 259 PCL for now wouldn't be a problem.  NetStandard is still fairly new stuff.  :-)

**Comment by bordoley** [comment]
Since it doesn't seem that netstandard has much adoption above and beyond PCL 259, for now I'll stick with focusing on a PCL 259 release this week. If you get around to submitting a PR, that would be much appreciated, but I don't have anyone specifically asking for it yet.

**Comment by bordoley** [comment]
Just released 1.1.0 to nuget. Let me know if you have any issues.
